version: '3.7'

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    security_opt:
    - seccomp:unconfined
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  # ts-node-docker:
  #   depends_on:
  #     - mysqldb
  #   restart: unless-stopped
  #   env_file: ./.env
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: base
  #   volumes:
  #     - ./src:/home/node/app/src
  #   container_name: ts-node-docker
  #   environment:
  #     - DB_HOST=mysqldb
  #     - DB_USER=$MYSQLDB_USER
  #     - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
  #     - DB_NAME=$MYSQLDB_DATABASE
  #     - DB_PORT=$MYSQLDB_DOCKER_PORT
  #   stdin_open: true
  #   tty: true
  #   expose:
  #     - $NODE_DOCKER_PORT
  #   ports:
  #     - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
  #   command: npm run dev
volumes: 
  db: